#!/bin/bash
# -*- ENCODING: UTF-8 -*-
echo vorap13 | sudo --stdin chown -R vorap:vorap app database tests routes resources/views  node_modules .env config phpunit.xml  
echo vorap13 | sudo --stdin chmod -R 777 storage resources/js vendor/phpunit
