FROM php:8.2-fpm

# новое  Здесь добавляем пользователя vorap с твоим UID и GID
# ARG UID
# ARG GID
#------------------------

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    npm \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libmagickwand-dev

RUN docker-php-ext-install pdo_mysql

# Установка Imagick
RUN pecl install imagick \
    && docker-php-ext-enable imagick

# Установка GD с поддержкой изображений
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# PHP настройки
RUN echo "upload_max_filesize=10M" >> /usr/local/etc/php/conf.d/uploads.ini && \
    echo "post_max_size=12M" >> /usr/local/etc/php/conf.d/uploads.ini && \
    echo "memory_limit=256M" >> /usr/local/etc/php/conf.d/uploads.ini

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer




# новое для vorap
# RUN groupadd -g ${GID} vorap && \
#     useradd -u ${UID} -g ${GID} -m vorap

# RUN if ! getent group ${GID} >/dev/null; then \
#     groupadd -g ${GID} vorap; \
#     fi && \
#     useradd -u ${UID} -g ${GID} -m vorap    

# Переключаемся на пользователя vorap
#USER vorap
#-------------------------

WORKDIR /var/www
COPY . .

